try to fix 3.ci coverage report

diff --git a/.github/workflows/3.ci_jobs.yml b/.github/workflows/3.ci_jobs.yml
--- a/.github/workflows/3.ci_jobs.yml
+++ b/.github/workflows/3.ci_jobs.yml
@@ -54,13 +54,20 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: coverage-report
-          path: ${{ env.TESTS_PATH }}/${{ env.TEST_REPORT_PATH }}
+          path: ${{ env.TEST_REPORT_PATH }}
           retention-days: 14
+
+      - name: List generated report
+        run: |
+          echo "=== workspace root ==="
+          pwd
+          echo "=== contents ==="
+          ls -R ${{ env.TEST_REPORT_PATH }}|| echo "Folder not found"
 
       - name: Upload pages artifact
         uses: actions/upload-pages-artifact@v3
         with:
-          path: ${{ env.TESTS_PATH }}/${{ env.TEST_REPORT_PATH }}
+          path: ${{ env.TEST_REPORT_PATH }}
 
 
   deploy-pages:
