try to fix documentation-generation and test-coverage in workflow

diff --git a/.github/workflows/ci_jobs.yml b/.github/workflows/ci_jobs.yml
--- a/.github/workflows/ci_jobs.yml
+++ b/.github/workflows/ci_jobs.yml
@@ -57,11 +57,13 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+          cd ${{ steps.latest.outputs.latest-stage-folder }}
+          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "missing requirements.txt file, aborting"; exit 1; fi
 
       - name: Generate coverage report for tests 
         run: |
           pip install pytest pytest-cov
+          cd ${{ steps.latest.outputs.latest-stage-folder }}
           python -m pytest --cov=tests --cov-report=term-missing --cov-report=html:${{ env.TEST_REPORT_PATH }}
 
       - name: Upload HTML coverage artifact
@@ -96,9 +98,14 @@ jobs:
         with:
           python-version: ${{ env.PYTHON_VERSION }}
 
-      - name: generate code documentation using pdoc
+      - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
+          cd ${{ steps.latest.outputs.latest-stage-folder }}
+          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "missing requirements.txt file, aborting"; exit 1; fi
+
+      - name: generate code documentation using pdoc
+        run: |
           pip install pdoc
           cd ${{ steps.latest.outputs.latest-stage-folder }}
           pdoc app/ --output-dir docs --docformat google
